# Generated by Django 3.1.3 on 2020-11-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-title',)},
        ),
    ]
